
#ifndef _DRIVER_CG_ZIGBEE_H_
#define _DRIVER_CG_ZIGBEE_H_

typedef enum {
	CZ_CMD_DEVICE_DISCOVER = 0x9101,
	CZ_CMD_DEVICE_DISCOVER_RESP = 0x9102,
	CZ_CMD_GET_STATUS = 0x9111,
	CZ_CMD_GET_STATUS_RESP = 0x9112,
	CZ_CMD_SET_STATUS = 0x9113,
	CZ_CMD_STATUS_CHANGED = 0x9114,
	CZ_CMD_EVENT = 0x9121,
	CZ_CMD_DO_ACTION = 0x9131,
	CZ_CMD_KEEP_ALIVE = 0x9141,
	CZ_CMD_RESULT = 0x9191,
	CZ_CMD_LAST,
} CZ_CMD_T;

typedef enum {
	CZ_PKT_TYPE_UC = 0,
	CZ_PKT_TYPE_BC,
	CZ_PKT_TYPE_MC,
	CZ_PKT_TYPE_LAST,
} CZ_PKT_TYPE_T;

#endif

