
#ifndef _HSB_DEVICE_H_
#define _HSB_DEVICE_H_

typedef enum {
	HSB_DEV_CLASS_SOCKET = 0,
	HSB_DEV_CLASS_SWITCH,
	HSB_DEV_CLASS_LAMP,
	HSB_DEV_CLASS_SENSOR,
	HSB_DEV_CLASS_REMOTE_CONTROL,
	HSB_DEV_CLASS_CAMERA,
	HSB_DEV_CLASS_SOUND_BOX,
	HSB_DEV_CLASS_DOORBELL,
	HSB_DEV_CLASS_ENTRANCE_GUARD,
	HSB_DEV_CLASS_TV,
	HSB_DEV_CLASS_AIR_CONDITIONING,
	HSB_DEV_CLASS_CURTAIN,
	HSB_DEV_CLASS_FRIDGE,
	HSB_DEV_CLASS_AIR_CLEANER,
	HSB_DEV_CLASS_WATER_HEATER,
	HSB_DEV_CLASS_OVEN,
	HSB_DEV_CLASS_MICROWAVE_OVEN,
	HSB_DEV_CLASS_LAMPBLACK,
	HSB_DEV_CLASS_FAN,
	HSB_DEV_CLASS_WARMING_OVEN,
	HSB_DEV_CLASS_HEATING,
	HSB_DEV_CLASS_STB,
	HSB_DEV_CLASS_BRACELET,
	HSB_DEV_CLASS_CUP,
	HSB_DEV_CLASS_ROUTER,
	HSB_DEV_CLASS_WASHER,
	HSB_DEV_CLASS_ELECTRIC_COOKER,
	HSB_DEV_CLASS_FAX,
	HSB_DEV_CLASS_PRINTER,
	HSB_DEV_CLASS_LAST,
} HSB_DEV_CLASS_T;

typedef enum {
	HSB_INTERFACE_WIFI = 0,
	HSB_INTERFACE_ZIGBEE,
	HSB_INTERFACE_BLUETOOTH,
	HSB_INTERFACE_IR,
	HSB_INTERFACE_NFC,
	HSB_INTERFACE_AM,
	HSB_INTERFACE_FSK,
	HSB_INTERFACE_LAST,
} HSB_INTERFACE_T;

typedef enum {
	HSB_SENSOR_TYPE_IR = 0,
	HSB_SENSOR_TYPE_DW,
	HSB_SENSOR_TYPE_FROG,
	HSB_SENSOR_TYPE_GAS,
	HSB_SENSOR_TYPE_LIGHT,
} HSB_SENSOR_TYPE_T;

typedef enum {
	HSB_STATUS_TYPE_ON_OFF = 0,
	HSB_STATUS_TYPE_BRIGHTNESS,
	HSB_STATUS_TYPE_COLOR,
	HSB_STATUS_TYPE_RECORD_ON_OFF,
	HSB_STATUS_TYPE_WORK_MODE,
} HSB_STATUS_TYPE_T;

typedef enum {
	HSB_WORK_MODE_HOME = 0,
	HSB_WORK_MODE_OUTSIDE,
	HSB_WORK_MODE_GUARD,
} HSB_WORK_MODE_T;

typedef enum {
	HSB_ACT_TYPE_ALARM = 0,
	HSB_ACT_TYPE_REMOTE_CONTROL,
} HSB_ACTION_TYPE_T;

typedef enum {
	HSB_EVT_STATUS_UPDATED = 0,
	HSB_EVT_DEV_UPDATED,
	HSB_EVT_SENSOR_TRIGGERED,
	HSB_EVT_SENSOR_RECOVERED,
	HSB_EVT_MODE_CHANGE,
} HSB_EVT_T;

#endif

