
#ifndef _HSB_ERROR_H_
#define _HSB_ERROR_H_

typedef enum {
	HSB_E_OK = 0,
	HSB_E_INVALID_MSG,
	HSB_E_NOT_SUPPORTED,
	HSB_E_BAD_PARAM,
	HSB_E_NO_MEMORY,
	HSB_E_ENTRY_EXISTS,
	HSB_E_ENTRY_NOT_FOUND,
	HSB_E_ACT_FAILED,
	HSB_E_OTHERS,
	HSB_E_UNDEFINED_8,
	HSB_E_UNDEFINED_9,
	HSB_E_UNDEFINED_10,
	HSB_E_UNDEFINED_11,
	HSB_E_UNDEFINED_12,
	HSB_E_UNDEFINED_13,
	HSB_E_UNDEFINED_14,
	HSB_E_UNDEFINED_15,
	HSB_E_LAST,
} HSB_ERROR_NO_T;

#endif

